### ISSUE TITLE
Typo in Kawasaki's iptables setup?

### ISSUE THREAD

**Issue by CFSworks** [cloudfoundry/guardian#106]
I'm debugging an issue very similar to #80, where my containers cannot reach the internet from Debian Stretch. In the process, I have encountered a perplexing iptables rule that seems to be a typo.

The rule in question is [here](https://github.com/cloudfoundry/guardian/blob/14492910a6bdd67dce8df1e97ef69130fd6d05f2/kawasaki/iptables/global_chains.go#L133), where a blanket forwarding rule is added to `w--forward` to allow all inbound (is that from the perspective of the container or host?) traffic. This rule doesn't make sense, however, as it's a rule that matches when the input interface is the default internet interface, but is added to the `${filter_forward_chain}`, which is only consulted for traffic arriving on an input interface starting with `${GARDEN_NETWORK_INTERFACE_PREFIX}`. Put another way, it's a rule that will never get triggered (except for host interfaces that begin with w, like wireless interfaces).

This rule makes sense if it should be `-o` instead of `-i`, as that allows all traffic inbound from containers if it's destined to the internet. Unfortunately, the use of the words "inbound" and "outbound" is ambiguous in the context of FORWARD, so I can't fully understand the intended purpose of this rule. In any case, I (hex) edited my local copy of Concourse to change that `-i` to a `-o` and my containers can reach the internet now.

Am I understanding the purpose of this rule correctly? Or is this just a dead rule and I should be looking for a missing rule in the `w--instance` chains to let the containers on the internet?

**Comment by rosenhouse** [comment]
Not a Gardener, but I have a bit of info.
- All these rules are written into the host network namespace, so they are from that perspective
- So the rule in question looks dead to me -- it won't ever get hit.
- Pretty sure it's not a "typo."  If you changed it to a `-o` then a bunch of acceptance tests of Garden would start failing, since traffic out of the container is regulated at run-time by a combination of [DenyNetworks](https://github.com/cloudfoundry/guardian/blob/3092edfe24053dea578ce528a6518b76e57a209e/guardiancmd/command.go#L244) and [NetOutRule](https://godoc.org/code.cloudfoundry.org/garden#NetOutRule)s.

**Comment by julz** [comment]
@CFSworks gonna close this because I think @rosenhouse answered as well as we could :) Feel free to re-open (or talk to us in #garden channel on slack) if there are questions we missed
