### ISSUE TITLE
iptables occasionally fails with 'resource temporarily unavailable'

### ISSUE THREAD

**Issue by vito** [cloudfoundry/guardian#36]
See also:

* https://github.com/concourse/concourse/issues/441
* https://ci.concourse.ci/pipelines/main/jobs/bin-testflight/builds/441

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#119662101](https://www.pivotaltracker.com/story/show/119662101) iptables occasionally fails with 'resource temporarily unavailable'


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by williammartin** [comment]
Hi @vito, can you tell us more information, such as: OS you're using, which version of Guardian, and provide a working link because https://ci.concourse.ci/pipelines/main/jobs/bin-testflight/builds/441 doesn't seem to load for us.

It also looks like in the concourse binaries you are compiling from source and apt-getting iptables? Just wondering whether there is anything funny going on.

Also, if this is on Ubuntu, do you build a RC version of concourse-lite we can get ahold of?

Thanks,

Will / @albertoleal

**Comment by vito** [comment]
OS is the BOSH ubuntu trusty stemcell. The binaries are vendoring iptables v1.4.21, which is the same version as the garden-runc release. Guardian version is whichever sha was in v0.2.0.

IPTables v1.4.21 is built from source and embedded in our binaries, and added onto the `$PATH` so they won't be using the host's `iptables` version. I've removed the `apt-get` since it shouldn't be necessary anymore.

You can grab an RC here: https://github.com/concourse/bin/releases/tag/v1.3.0-rc.90

**Comment by vito** [comment]
Here are some failed builds:

* https://ci.concourse.ci/builds/1331
* https://ci.concourse.ci/builds/996
* https://ci.concourse.ci/builds/989
* https://ci.concourse.ci/builds/855
* https://ci.concourse.ci/builds/577
* https://ci.concourse.ci/builds/404
* https://ci.concourse.ci/builds/369
* https://ci.concourse.ci/builds/339

That this accounts for ~50% of our failed `bin-testflight` builds.

**Comment by vito** [comment]
@williammartin I just noticed something which kinda throws a wrench into things:

https://github.com/cloudfoundry-incubator/guardian/blob/master/kawasaki/iptables/iptables.go#L57

Guardian hardcodes the path to `iptables` as `/sbin/iptables`, which doesn't allow us to control the version of `iptables` that it uses. It's probably not even using the version of `iptables` contained in the BOSH release, either.

Can we make this an injectable flag instead, just like all the other binary paths? Then I won't need to do `$PATH` munging either.

**Comment by vito** [comment]
Based on that finding it turns out the `bin-testflight` build was indeed depending on whatever version of `iptables` were apt-getting. So if 1.4.21 doesn't demonstrate this issue and we can fix the vendoring problem then that might be all we need.

**Comment by julz** [comment]
Well this explains a LOT :). Feeding in a path (with a default) seems
totally reasonable to me, and I'd almost bet it fixes the problem here.Unless stated otherwise above:
IBM United Kingdom Limited - Registered in England and Wales with number 741598. 
Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU

**Comment by williammartin** [comment]
Presumably the ability to pass in a path is a feature you'd desire whether or not it resolves this issue. We should put something in the backlog for this.

**Comment by vito** [comment]
@julz sounds good, or you could just label that feature with this issue to have it auto-finish it (`cloudfoundry-incubator/guardian#36`)

**Comment by robdimsdale** [comment]
I see this quite often in my concourse (maybe one in 5 containers). I'm using the binary directly on `ami-ddf13fb0`:

```
bash-4.3# uname -ra
Linux 49e0400d-2adb-4b2a-6ea0-39f45610cd6e 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 GNU/Linux
```

```
bash-4.3# which iptables
/usr/sbin/iptables
bash-4.3# iptables --version
iptables v1.6.0
```

**Comment by mdomke** [comment]
I'm seeing this also quite often using concourse 1.3.1:

```
bash-4.3# uname -a
Linux b2ae8224-beb2-4c3d-5823-0bfbed375e8d 4.6.3-1.el7.elrepo.x86_64 #1 SMP Sat Jun 25 11:28:39 EDT 2016 x86_64 GNU/Linux
```

```
bash-4.3# which iptables
/usr/sbin/iptables
bash-4.3# iptables --version
iptables v1.6.0
```

**Comment by julz** [comment]
This should now be fixed in the latest concourse (the problem was that the system version of iptables was being used and that didn't end well, we now explicitly support passing a path to an iptables binary so we can ensure it's the expected version). Please re-open if this bug occurs on a recent version of concourse/garden. Thanks!
