### ISSUE TITLE
Smarter DNS defaults

### ISSUE THREAD

**Issue by vito** [cloudfoundry/guardian#42]
Users running Concourse often run into issues with DNS. For example, out of the box, Ubuntu 16.04 will default `/etc/resolv.conf` to something like:

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search localdomain
```

Any `nameserver` referring to a local address won't be reachable by a container, as they're in their own network. So, the container ends up without working DNS

Docker filters local entries out, and then if the set is empty, adds Google's DNS servers by default (8.8.8.8 and 8.8.4.4):

https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/

This seems like a reasonable approach to me.

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#127919629](https://www.pivotaltracker.com/story/show/127919629) Smarter DNS defaults


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by cirocosta** [comment]
This also apply for docker user defined networks, right? As it uses `127.0.0.11`by default in such situation

**Comment by vito** [comment]
@cirocosta Yeah - anything in the `127.x.x.x` address range, I'd expect.

**Comment by deitch** [comment]
Aha! I have been struggling with this, debugging it slowly. See https://github.com/starkandwayne/concourse-tutorial/issues/45 in the tutorials.

My $0.02 (do as you will): I think we should have dnsmasq or some other such simpler DNS server listening on all of the Linux bridges created. It will then just forward all requests to whatever is set where it is running. Thus, a request would go:

`runc` container --> bridge --> dnsmasq (host) --> default DNS

Since dnsmasq is on the host itself (or in the docker container), it will then resolve whatever is on the host.

This abstracts the host config from the `runc` container config. Much easier than trying to figure out all of the permutations and edge cases for copying `/etc/resolv.conf` over.

**Comment by vito** [comment]
Just to ping again as this is coming up pretty frequently from our users; it seems to be becoming common to have `127.0.0.X` entries in `/etc/resolv.conf` which confuses the containers quite a bit.

**Comment by donaldguy** [comment]
Can confirm still an issue, I just ran into it in concourse as well https://concourseci.slack.com/archives/C07RY25QF/p1490996708850846

**Comment by jelledrm** [comment]
Any updates on this? I have problems resolving docker hostnames from inside garden containers. See http://stackoverflow.com/questions/43265023/concourse-ci-resolve-docker-hostname for more info

**Comment by rosenhouse** [comment]
I believe that the logic that y'all are looking for is now present in Guardian.

A recent set of commits added more flexibility for Guardian's DNS logic.  In particular, it [now filters out `127.0.0.x` addresses](https://github.com/cloudfoundry/guardian/blob/58d21e4/kawasaki/dns/nameservers_determiner.go#L33).

Also, there are now [two flags for controlling the DNS for the container](https://github.com/cloudfoundry/guardian/blob/58d21e4cdc8c2ca8330760be81508a50cdadb632/guardiancmd/command.go#L205-L206): `dns-server` and `additional-dns-server`.

Not sure when this will land in the next release of Concourse.

**Comment by deitch** [comment]
> A recent set of commits added more flexibility for Guardian's DNS logic. In particular, it now filters out 127.0.0.x addresses. Also, there are now two flags for controlling the DNS for the container: dns-server and additional-dns-server.

@rosenhouse I don't think it answers it. 

* If you filter out `127.0.0.x`, and that is all there is in a docker container, the runc container will have nothing
* Adding two new flags means additional config work that is very difficult to figure out.

For all of these, the place where it is running (distinct from the runc container) has DNS defaults that are accessible there, and only there. You want all DNS requests (unless *explicitly* overrides via those options) to go to the wrapping (host, docker, etc.)'s IP stack, and from there to whatever it is configured. I don't see much beyond an additional bridge or iptables rule.

**Comment by rosenhouse** [comment]
Hmm, it's not clear to me which features belong in Garden and which features belong in the Concourse distribution (e.g. Docker image).

For comparison, we're giving Cloud Foundry containers access to BOSH DNS with a 3-step process:

1. BOSH DNS server listens on 169.254.0.2 on the host
2. Setting the Garden container's resolv.conf to list only that address
3. Writing an iptables INPUT rule on the host to allow the container to reach that address

We're [doing steps 2 & 3 via a CNI plugin](https://github.com/cloudfoundry-incubator/cf-networking-release/blob/63d5e14/src/cni-wrapper-plugin/cni_wrapper_plugin_test.go#L340) called by [a garden external networker](https://github.com/cloudfoundry-incubator/cf-networking-release/tree/develop/src/garden-external-networker).

For Concourse, maybe step 1 is that you run DNSMasq on the "host" (e.g. inside the docker image).  Step 2 could be one of the DNS flags for Garden.   But Step 3 is a bit messy -- maybe its an external networker.  Maybe it's a new feature in Kawasaki.

**Comment by deitch** [comment]
I remain somewhat fuzzy on the relationships between all of the components, since I came to this from Concourse, run inside a docker container, which in turn launched runc containers. (a lot of digging to get to the issue) The docker container has resolv.conf set to `127.0.0.11`, so Concourse thinks that is a legit DNS (not that different than the `169.254.0.2` structure you have on CF w/ BOSH DNS). 

However, when you already are in a docker container, you cannot really run iptables to change host settings (unless you are running `--privileged` or the equivalent). 

So, yeah, dnsmasq or similar lightweight DNS server on the "host" (docker container) makes sense, and then you can just add it to resolv.conf in the runc container. No need for iptables for that either.

**Comment by pivotal-topher-bullock** [comment]
Got this working on a `docker-compose`d Concourse on OSX  by running a lightweight DNS proxy ( https://github.com/gophergala/dnsp ) on the worker container in Docker, and adding that container's `10.x.x.x` IP as a nameserver in `/etc/resolv.conf`.  Going to solve this in the Concourse Docker containers in concourse/concourse#1145

IMO this is outside of Guardian's realm of responsibility. Guardian shouldn't worry about setting up nameservers for whatever wacky embedded DNS server the host is running on loopback and proxying to it; and as @rosenhouse said the functionality for configuration is already present.

**Comment by julz** [comment]
Thanks y'all - I'm going to close this since I don't think it's going to make sense for garden to work on this since we're hoping to eventually end-of-life the internal networker in favour of the container networking team's CNI plugin which should allow custom stuff such as this to be done externally to garden. Hopefully @rosenhouse's suggestion above provides a decent approach in the meantime.
