### ISSUE TITLE
Default port-pool overlaps with linux default ephemeral port range

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/guardian#67]
I see that Guardian defaults to using a port range from 60000-65000:

```go
Network struct {
    PortPoolStart  uint32 `long:"port-pool-start" default:"60000" description:"Start of the ephemeral port range used for mapped container ports."`
    PortPoolSize  uint32 `long:"port-pool-size"  default:"5000"  description:"Size of the port pool used for mapped container ports."`
}
```
[ [source code](https://github.com/cloudfoundry/guardian/blob/master/guardiancmd/command.go#L208-L209) ]

I also see that Linux uses part of that range for the local ephemeral port range:

```
$ uname -a
Linux 4f4b699f-80f6-4a63-880b-f0917d519000 4.4.0-59-generic #80~14.04.1-Ubuntu SMP Fri Jan 6 18:02:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/sys/net/ipv4/ip_local_port_range
32768	60999
```

We don't want those two ranges to overlap, correct?

**Comment by ematpl** [comment]
Yeah, I had filed https://www.pivotaltracker.com/story/show/117415775 about that a while ago (seems that the upper end of the range has decreased to 60999 since then). I think it would be a problem only when Garden tries to allocate a container port in that range when some other process is using it? Would be interesting to see if this theoretical collision has caused failures in the wild.

**Comment by rosenhouse** [comment]
Cool, I wasn't sure if I was missing something.

More importantly, I'm going to fix this in the [CF Networking plugin](https://github.com/cloudfoundry-incubator/cf-networking-release/blob/650e067/jobs/garden-cni/spec#L20)

**Comment by julz** [comment]
Yeah, looks the story for this got a bit lost down the bottom of the couch/backlog, I pulled it up a bit. Thanks!
