### ISSUE TITLE
Hosts should contain both ipv4 AND ipv6 loopback

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/guardian#79]
(coming from concourse-land)

Right now, when I spin up concourse (which ofc uses guardian as the backend) my container `/etc/hosts` file appears to be blown away and replaced with something like this:

```
127.0.0.1	localhost
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	98664ae95097
```

Some of the concourse folks believe this is either guardian [mapping a hosts file](https://github.com/cloudfoundry/guardian/blob/a86da09a507c0d69c7765776f2f0ab607aadf41a/rundmc/depot/dirdepot.go#L64-L70) or some default somewhere in guardian.

It'd be great if both `127.0.0.1    localhost` as well as `::1    localhost` were provided for those of us running tests that have to use `::1` ipv6 loopback in our tests. 🙂

**Comment by julz** [comment]
Sorry for dropping the ball on this, I've scheduled the story. We're also happy to receive a pull request if you'd like to speed it up!

**Comment by craigfurman** [comment]
Bosh Linux stemcells [disable ipv6 using a kernel boot parameter](https://lists.cloudfoundry.org/archives/list/cf-bosh@lists.cloudfoundry.org/thread/MR35HYCIZW35F37PWYNBYOYVV7J7QGUJ/), so you might not get much use out of this feature yet. 😉 

Even so, adding it

**Comment by craigfurman** [comment]
Delivered in garden-runc-release [76d0e507a413d1057687f5fab276a73536efc4ce](https://github.com/cloudfoundry/garden-runc-release/commit/76d0e507a413d1057687f5fab276a73536efc4ce)

**Comment by williammartin** [comment]
@jadekler Unfortunately we've backed out this change in https://github.com/cloudfoundry/guardian/commit/0984e8accf7ccc5564ce64d23f4fe8ec1af1e728 because it is breaking various environments that try to make a connection and choose the ipv6 loopback even when ipv6 is disabled in the kernel (i.e. in the bosh stemcell).

What can be done now is that you can pass:

`--additional-host-entry "::1 localhost"` to gdn on startup and this entry will be appended to your container's /etc/hosts file.

Let me know if you have any questions or we can chat about it at OSS next week!
