### ISSUE TITLE
Use of tcpdump in a buildpack container

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/guardian#90]
We'd like to offer our `cf ssh` users the possibility to use tools like `tcpdump` in their (buildpack) containers. 

This currently seems to be impossible: the `tcpdump` binary is (intentionally) missing in the rootfs - but after copying it to the container, the `vcap` user lacks the necessary privileges:
```
$ ./tcpdump -s 0 -w pcap.out -i wip0f8df9rl11-1 tcp port 8080
tcpdump: wip0f8df9rl11-1: You don't have permission to capture on that device
(socket: Operation not permitted)
``` 

I found this [thread on the mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/2L3XLSDBEGTU54QBPYQSG4IQ3NORWDXH/) which explains that the required privilege (i.e. `CAP_NET_ADMIN `) is intentionally dropped for security reasons. However, the thread is quite old and refers to garden linux. 

How does the situation look like with guardian/runc? Is there a possibility to offer the required privileges to end users?

When looking at the [source code](https://github.com/cloudfoundry/guardian/blob/89b3bf4ad202cc6f17aa749353e9989eca831a12/guardiancmd/command.go#L72), it looks like root in the container obtains the privilege; the[ CF doc](https://docs.cloudfoundry.org/concepts/container-security.html) states otherwise:
> CF drops the following Linux capabilities for all container processes. Every dropped capability limits what actions the root user can perform. 
... 
CAP_NET_ADMIN

(But this anyway only applies to the root users and would not help our vcap users much)

**Comment by julz** [comment]
Hi @MatthiasWinzeler, as you've guessed we very intentionally drop the CAP_NET_ADMIN capability in the container (the list of capabilities you linked to above is the capabilities a *privileged* container will receive, unprivileged containers -- which are the default for CF -- receive [the list here](https://github.com/cloudfoundry/guardian/blob/master/guardiancmd/command.go#L53)). 

The reason we do not enable the capability is because it has a large surface area for potential exploits compared to minimal valid use cases for Cloud Foundry applications, and would potentially allow containers to try to do things like changing their IPs or sniffing packets which for obvious reasons we don't want to allow. Unfortunately the capability system is quite broad and there's no granular way of letting you use tcpdump without opening up quite a lot of other things we'd feel pretty uncomfortable allowing.

Maybe if you tell us more about your use case we could think about other ways the platform could help. For example we already allow logging of connection destinations leaving containers, perhaps the platform itself - maybe via a route service? - could do this logging for you?

**Comment by rbgigo** [comment]
Hi julz

I am not fully familiar with all the capabilities that have been dropped with CAP_NET_ADMIN. I understand to reduce the attack surface it might make sense to have this removed or disabled in some production environment. Also I read that it is not possible to enable single capabilities out of CAP_NET_ADMIN. 

In our setup we have two reverse proxies in addition to the GO-Router in between e.g. the browser client and the backend appserver running in some Warden container. This access path is secured using TLS which is a big obstacle in the way when it comes to troubleshooting HTTP related issues. In our classic on-premises setup using tcpdump capturing the appserver's ingress and egress traffic has shown to be the most efficient way, not requiring any actions from the application owner point of view, except providing the support team with some reproducible case.

In the this classic setup supporters are not logging in as root, rather they call tcpdump using sudo. The latter you can tweak in a way to lock it down as much as needed. Operating like this is fully in line with our information security policy, is not seen as a high risk exposure, especially when used in a non-production environment. 

Hope this gives you the necessary background of our requirement.

**Comment by julz** [comment]
Hi @rbgigo, understood that using sudo in this way would often be safe, however in a container context we can't rely on sudo having been locked down properly or a malicious user could - for example - push a docker-image-based container with a custom `/etc/sudoers` file and get arbitrary root permissions. For this reason in CF we set up the containers so that _even if a user acquires root permissions_ they cannot perform potentially harmful actions. Understood though that in this case that blocks your current use case because the "root" user in the container doesn't have permissions to do tcpdump.

cc @rusha19 - since I think this _might_ potentially be implementable via the network stack rather than by relaxing the container security

**Comment by rosenhouse** [comment]
cc: @jaydunk @cloudfoundry/cf-container-networking

**Comment by rbgigo** [comment]
Hi all, thanks for all the comments, everything is comprehensible. I should have mentioned that we use Cloud Foundry in kind of a private cloud setup, however the underlying HW is shared with other customers but it is definitely not a public cloud setup. That said, to some extent from a security point of view we can look at it a bit more relaxed. Can you give me a bit more details regarding the possible alternate approach via the network stack?

**Comment by julz** [comment]
WRT the network stack what I'm thinking is rather than making the user run a privileged binary inside the container where they don't have permissions we could add functionality to the networking stack _outside_ the container to forward incoming packets out to the logging system. We already do this to log the first packet of every connection going out from the container for operators so it seems like _potentially_ we could do something similar so that platform users could generically request a dump of the traffic arriving at their container's network port. 

Having said that this'd be a feature request for [cf-container-networking](https://github.com/cloudfoundry-incubator/cf-networking-release) rather than garden and I've no idea how much interest they'd have in doing such a thing! :)

For now since I don't think garden can enable this without relaxing security rules that we wouldn't feel comfortable relaxing I'm going to close the issue.
